/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    OracleReader: {
      address: "0x662ca006be8dbe05545ac9af490460c217fda562",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "chronicle_",
              type: "address",
              internalType: "address",
            },
            {
              name: "selfKisser_",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "chronicle",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IChronicle",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "read",
          inputs: [],
          outputs: [
            {
              name: "val",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "selfKisser",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISelfKisser",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
